services:
  database:
    container_name: db
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_USER=johndoe
      - POSTGRES_PASSWORD=randompassword
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - network

  cavalo-marinho:
    depends_on:
      - database
    image: osmanosbrasil/castor
    environment:
      DATABASE_URL: postgres://johndoe:randompassword@database:5432/mydb?schema=public
    ports:
      - "4000:4000"
    networks:
      - network

networks:
  network:
    driver: bridge

volumes:
  db:
    driver: local
